### ISSUE TITLE
Passport 7 Fails

### ISSUE THREAD

**Issue by velkymx** [yaquawa/laravel-passport-binary-uuid-adapter#1]
Using Laravel 5.6 and passport 7

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yaquawa/laravel-passport-binary-uuid-adapter v1.0.0 requires laravel/passport ^6.0 -> satisfiable by laravel/passport[6.0.x-dev].
    - yaquawa/laravel-passport-binary-uuid-adapter v1.0.1 requires laravel/passport ^6.0 -> satisfiable by laravel/passport[6.0.x-dev].
    - yaquawa/laravel-passport-binary-uuid-adapter v1.0.2 requires laravel/passport ^6.0 -> satisfiable by laravel/passport[6.0.x-dev].
    - yaquawa/laravel-passport-binary-uuid-adapter v1.0.3 requires laravel/passport ^6.0 -> satisfiable by laravel/passport[6.0.x-dev].
    - Conclusion: don't install laravel/passport 6.0.x-dev
    - Installation request for yaquawa/laravel-passport-binary-uuid-adapter ^1.0 -> satisfiable by yaquawa/laravel-passport-binary-uuid-adapter[v1.0.0, v1.0.1, v1.0.2, v1.0.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by yaquawa** [comment]
@velkymx 
Yeah, it's because of this line https://github.com/yaquawa/laravel-passport-binary-uuid-adapter/blob/master/composer.json#L23

I have not tested it with Passport version 7 yet, may be you can try it as a [local repository](https://getcomposer.org/doc/05-repositories.md#path) first.

**Comment by nolanpro** [comment]
@yaquawa we tried this out with [my fork](https://github.com/nolanpro/laravel-passport-binary-uuid-adapter/commit/19416f804abdeb5fd252f9d2773bffb45023be3e) on [process maker feature/650](https://github.com/ProcessMaker/bpm/blob/feature/650/composer.json#L25) branch and its been working fine for a few weeks now. Could you update yours? Thanks!

**Comment by yaquawa** [comment]
OK, just updated the `composer.json` to expand the required version to ver.7 of Password.
